[theme]
name = "gruvbox-dark"
[theme.overrides]
alternating_tint_bg = "#14100e"

[icons]
name = "awesome"
[icons.overrides]
backlight_empty = "☀️"
backlight_partial1 = "☀️"
backlight_partial2 = "☀️"
backlight_partial3 = "☀️"
backlight_full = "☀️"

[[block]]
block = "pacman"

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = "{percentage}% {time}"

#[[block]]
#block = "speedtest"

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB"

[[block]]
block = "cpu"
interval = 1
format = "{barchart}{utilization}%"

[[block]]
block = "time"
interval = 1
format = "%y/%d/%m %a %T"
